# Generated by Django 6.0.2 on 2026-02-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('IN', 'Checked In'), ('OUT', 'Checked Out')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
