# Generated by Django 6.0.2 on 2026-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_status_alter_attendance_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=20)),
                ('face_embedding', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
